spring:
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled=true: