server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: my-service
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled=true:
